A function declaration without a prototype is deprecated in all versions of C fix
drivers/misc/mediatek/base/power/mcdi/mtk_mcdi_governor.c:197:5: error: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
int get_cluster_off_token(cpu)

Signed-off-by: atharvnegi <atharvnegi2951@gmail.com>