sound/soc: mediatek: nuke unused variable
sound/soc/mediatek/fs1815n/fsm_core.c:1026:10: error: variable 'i2sctrl' set but not used [-Werror,-Wunused-but-set-variable]
        uint8_t i2sctrl;

Signed-off-by: Egii <regidesoftian@gmail.com>
Change-Id: I05fb4e9642a21404fb9c029dd43138df25d0cdff
Signed-off-by: Mikazuuu07 <mikazuuu07@nusantararom.org>
Signed-off-by: atharvnegi <atharvnegi2951@gmail.com>